[package]
name = "rwatch"
version = "0.1.0"
authors = ["Faheetah <Faheetah@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "0.4.0"
notify = "5.0.0-pre.3"
regex = "1"
